version: '3.8'

services:
  # database section
  rimidentitydb:
    image: mcr.microsoft.com/mssql/server:2019-latest
    container_name: rimidentitydb
    environment:
        SA_PASSWORD: "Passw0rd!"
        ACCEPT_EULA: "Y"
    volumes:
        - rim_identity_sqlserver_data:/var/opt/mssql
    restart: always
    ports:
        - 1436:1433

volumes:
    rim_identity_sqlserver_data:
       external: false
    